# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80307637c06ad529ae545754aee248ec4aafec47f75e89db1f9dc7c8cfa52fff17738332491ac0be51cd10e97d237f4a63b51ec99c04e89994d445adfa0d9f8d

test:
  secret_key_base: f1a24f30f0c4d83ff6b51ac340e2669d62644ee78be147f11aaefc1a82a04eb5673d732f11375e2f6c012fadcd51dd6d7354020f1ef786d0576a109d8045b207

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
